# Generated by Django 4.1.1 on 2022-10-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productModel',
            new_name='product',
        ),
    ]
