# Generated by Django 4.1.1 on 2022-12-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
